### ISSUE TITLE
Allow clearing of colData

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/SummarizedExperiment#19]
There doesn't seem to be an easy way to empty out the colData in a SE object. I would have liked to do:

```r
rowData(se) <- NULL # works
colData(se) <- NULL # fails, no method for "NULL"
```

This is occasionally necessary when trying to `cbind` different SE objects of different origins, where we want to clear out any differences in the column metadata. Perhaps the following bit of code would suffice:

```r
setReplaceMethod("colData", c("SummarizedExperiment", "NULL"),
    function(x, ..., value)
{
    value <- new("DataFrame", nrows=nrow(x))
    BiocGenerics:::replaceSlots(x, colData=value, check=FALSE)
})
```

Happy to put in a PR if people think that this is a good idea.

**Comment by hpages** [comment]
Just added this to SummarizedExperiment 1.15.10.

There are actually many things that `rowData<-` can do that `colData<-` can't (e.g. recycle the right value, take an ordinary data frame or a list, etc...) so maybe at some point we should address that.

H.
