### ISSUE TITLE
Convert ShallowSimpleListAssays into an S3 list

### ISSUE THREAD

**Issue by marcpaga** [Bioconductor/SummarizedExperiment#20]
Is there any simple way to convert a ShallowSimpleListAssays into a S3 list? Methods like `as.list` or `unlist` do not work. The current workaround that I use is as follows:

     assaysList <- lapply(1:length(assays(x)), function(i){
      assays(x)[[i]]
    })

I think a more simple approach should exist.

**Comment by PeteHaitch** [comment]
Does `as.list(assays(x))` give you what you want?
`assays()` returns a *List*, for which there as an `as.list()` method to convert it to a *list*.

**Comment by marcpaga** [comment]
You are right, it was a problem in my end that `as.list()` would not work for me. Thanks!

**Comment by PeteHaitch** [comment]
You're welcome. More generally, something that may be useful to know, the use of accessor methods (like `assays()` and `rowRanges()`) should be preferred over direct slot access (like `x@assays` or `x@rowRanges`) when working with S4 classes.
