### ISSUE TITLE
assayNames<- is reluctant to work

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/SummarizedExperiment#25]
This seems to occur if the dimnames of the underlying matrix differ from that of the SE:

```r
library(SummarizedExperiment)
mat <- matrix(1,1,1)
colnames(mat) <- "B"
rownames(mat) <- "GENE2"

se <- SummarizedExperiment(list(counts=mat))
colnames(se) <- "A"
rownames(se) <- "GENE1"

assayNames(se) <- "whee"
## Error in `assays<-`(`*tmp*`, withDimnames = FALSE, value = `*vtmp*`) :
##   current and replacement dimnames() differ
```

<details>
<summary>Session information</summary>

```
R version 3.6.0 Patched (2019-05-10 r76483)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/luna/Software/R/R-3-6-branch-dev/lib/libRblas.dylib
LAPACK: /Users/luna/Software/R/R-3-6-branch-dev/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] SummarizedExperiment_1.15.3 DelayedArray_0.11.1
 [3] BiocParallel_1.19.0         matrixStats_0.54.0
 [5] Biobase_2.45.0              GenomicRanges_1.37.11
 [7] GenomeInfoDb_1.21.1         IRanges_2.19.10
 [9] S4Vectors_0.23.12           BiocGenerics_0.31.4

loaded via a namespace (and not attached):
 [1] lattice_0.20-38        bitops_1.0-6           grid_3.6.0
 [4] zlibbioc_1.31.0        XVector_0.25.0         Matrix_1.2-17
 [7] tools_3.6.0            RCurl_1.95-4.12        compiler_3.6.0
[10] BiocManager_1.30.4     GenomeInfoDbData_1.2.1
```
</details>

**Comment by hpages** [comment]
Hi Aaron,

The `dimnames` setter for SE objects is at the root of the problem.

My understanding is that the _inner dimnames_ (i.e. the dimnames on the individual assays) are only allowed to be `NULL` or the same as the _outer dimnames_ (i.e. the dimnames of the SE object itself). This is actually enforced by the SE constructor:
```
library(SummarizedExperiment)
m <- matrix(1:12, nrow=4)
rowData <- DataFrame(stuff=11:14, row.names=letters[1:4])

se1 <- SummarizedExperiment(m, rowData=rowData)
dimnames(se1)
# [[1]]
# [1] "a" "b" "c" "d"
#
# [[2]]
# NULL

colnames(m) <- LETTERS[1:3]
se2 <- SummarizedExperiment(m, rowData=rowData)
dimnames(se2)
# [[1]]
# [1] "a" "b" "c" "d"
#
# [[2]]
# [1] "A" "B" "C"

rownames(m) <- LETTERS[1:4]
se3 <- SummarizedExperiment(m, rowData=rowData)
# Error in .validate_names(rownames, ans_rownames, "assay rownames()", "rowData rownames() / rowRanges names()") : 
#   assay rownames() must be NULL or identical to rowData rownames() /
#   rowRanges names()
```
Unfortunately, for some reason, this is not checked by the validity method for SummarizedExperiment objects.

Now when you do:
```
mat <- matrix(1,1,1, dimnames=list("B", "GENE2"))
se <- SummarizedExperiment(list(counts=mat))
dimnames(se) <- list("A", "GENE1")
```
you end up with an object that is "wrong" (even though `validObject(se)` returns `TRUE`):
```
dimnames(se)
# [[1]]
# [1] "GENE1"
#
# [[2]]
# [1] "A"

dimnames(assay(se, withDimnames=FALSE))
# [[1]]
# [1] "GENE2"
#
# [[2]]
# [1] "B"

validObject(se)
# [1] TRUE
```
This "wrong" object causes problems later when you do `assayNames(se) <- "whee"` or simply do the following no-op:
```
assays(se, withDimnames=FALSE) <- assays(se, withDimnames=FALSE)
# Error in `assays<-`(`*tmp*`, withDimnames = FALSE, value = new("SimpleList",  : 
#   current and replacement dimnames() differ
```

So one thing we can do is fix the `dimnames` setter by having it adjust (or drop) the _inner dimnames_ to keep them in sync with the new _outer dimnames_.

@mtmorgan: But why do we care about the _inner dimnames_ in the first place? Never really understood the motivation for this constraint. It feels arbitrary and counter productive to me. Couldn't we just ignore the _inner dimnames_? Benefits: simpler conceptual validity, simpler implementation of a few setters (`dimnames<-`, `assays<-`), faster code (adjusting the _inner dimnames_ could be expensive in some situations), and no more problems of the sort Aaron ran into. What could the downsides be?

If Martin has no objection, I'll remove this constraint.

**Comment by mtmorgan** [comment]
I think the inner dimnames are there for efficiency -- the most common way to access the data is `assay()`; having dimnames on the result is usually desired; it's expensive (causes the assay to be copied) to add them. This was motivated by a use case / problem Kasper Hansen had several years ago with large methylation arrays, I don't know whether his concerns are still relevant...

**Comment by hpages** [comment]
Thanks Martin. Just to clarify: right now the inner dimnames can be `NULL` so we already are in a situation where they don't necessarily match the outer dimnames. And `assay()` is already triggering copies when setting the outer dimnames on the returned assay (unless `withDimnames=FALSE` is used). I'm not proposing to change that. All I'm proposing is that we let the inner dimnames be anything,

**Comment by mtmorgan** [comment]
ok by me.

**Comment by hpages** [comment]
Done in SummarizedExperiment 1.15.5 (see commit 7df70dc87fe2dce6f8716b199d0a7163c856ef5d).

@LTLA This addresses your original issue so I'm closing this. Feel free to re-open if I missed something.
