### ISSUE TITLE
Extraction isn't working with ShallowSimpleListAssays on Bioc Devel 3.10

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/SummarizedExperiment#31]
I'm seeing a potential issue with `ShallowSimpleListAssays` pop up on Bioc Devel. Extraction of an assay (i.e. from a `SummarizedExperiment` object) doesn't seem to be working as expected, and returns:

```
Error in assays[[1]] : wrong arguments for subsetting an environment
```

Here's an example on a `RangedSummarizedExperiment`:

```
assays <- slot(object, "assays")

showClass("ShallowSimpleListAssays")
## Class "ShallowSimpleListAssays" [package "SummarizedExperiment"]
##
## Slots:
##
## Name:       .xData
## Class: environment
##
## Extends:
## Class "ShallowData", directly
## Class "Assays", directly
## Class "envRefClass", by class "ShallowData", distance 2
## Class ".environment", by class "ShallowData", distance 3
## Class "refClass", by class "ShallowData", distance 3
## Class "environment", by class "ShallowData", distance 4, with explicit
##   coerce
## Class "refObject", by class "ShallowData", distance 4
## Class "AssayData", by class "ShallowData", distance 5, with explicit
##   coerce
##

is.environment(assays)
## [1] TRUE

lapply(
    X = seq_along(assays),
    FUN = function(a) {
        assays[[a]]
    }
)
## Error in assays[[a]] : wrong arguments for subsetting an environment
```

See Travis CI job log for an example:
https://travis-ci.com/acidgenomics/bcbioRNASeq/jobs/219620463

**Comment by hpages** [comment]
Direct slot access is strongly discouraged in Bioconductor. Please use `assays(object)` instead of `slot(object, "assays")`. This will return a SimpleList object instead of a ShallowSimpleListAssays object. ShallowSimpleListAssays objects are not meant to be seen or manipulated directly by the end user.

Thanks,
H.

**Comment by mjsteinbaugh** [comment]
@hpages Normally I use `assays()` as recommended, but I had to use `slot()` in this case for my `updateObject()` method on an invalid object:
https://github.com/hbc/bcbioRNASeq/blob/master/R/updateObject-methods.R

Is there a better way to extract the assays as a list from an invalid object that inherits from SummarizedExperiment?

**Comment by mjsteinbaugh** [comment]
I thought of a way around this issue -- safe to close. Thanks!

**Comment by hpages** [comment]
FWIW if you absolutely have to use direct slot access in your `updateObject()` method, then subset with `getListElement()` instead of `[[`:
```
assays <- slot(object, "assays")
getListElement(assays, 1)
```
Note that this only works in Bioconductor >= 3.10.

Hope this helps.
