### ISSUE TITLE
Build an assay element to work from my own normalized count matrix

### ISSUE THREAD

**Issue by ramarquezo** [Bioconductor/SummarizedExperiment#32]
Hello, I have used  your scripts and work very well, thanks a lot! However I would like to build a summarizexperiment (se) from my own normalized matrix, I mean I want to store my matrix in an assay object to run it with summarizexperiment and create a summarise element. Sorry I completely got lost doing it, is there a parameter to use in summarizexperiment to tell the program what data use? I have the features=ebg that has worked with the bam files, so I want to use it with a matrix of FPKM´s I built using other software. I have just found tutorial to count from scratch from the bam files....

I appreciate a lot your help...

**Comment by lshep** [comment]
You can create a SummarizedExperiment through the standard constructor passing any matrix as the assay argument.  Is this what you mean? 

mock:
```
> mat = matrix(1:20, nrow=5)
> SummarizedExperiment(assays = mat)
class: SummarizedExperiment 
dim: 5 4 
metadata(0):
assays(1): ''
rownames: NULL
rowData names(0):
colnames: NULL
colData names(0):

```

**Comment by hpages** [comment]
Please note that SummarizedExperiment is a Bioconductor package. Any question about using Bioconductor packages should be asked on our support site (https://support.bioconductor.org/) where it will receive a lot more attention. Also the answers you will get will be seen by the community so will benefit other users facing the same difficulties. Make sure to check the Posting Guide before you create your post there.

GitHub is mostly for reporting bugs, pull requests, and other development-related issues/discussions.

Thanks,
H.

**Comment by ramarquezo** [comment]
Thanks a lot lshep, I'll try it, I think this is what I need....

**Comment by ramarquezo** [comment]
Thanks lshep, that's what I need, I'll try to pass my matrix with that....

**Comment by lshep** [comment]
@ramarquezo No problem but as @hpages said next time please use the support.bioconductor.org site for these types of questions.
