### ISSUE TITLE
Improving the performance when calling assays accessor on a SummarizedExperiment object?

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/SummarizedExperiment#40]
Hi,

I found an unnecessary memory duplication when operates on the object that is returned by the `assays` function. I think it is an unintentional behavior so I would like to discuss it here. Here is a simple example. 
```
nrows <- 10; ncols <- 10
counts <- matrix(0.0, nrows,ncols)
rse <- SummarizedExperiment(assays=SimpleList(counts=counts))
rse
```
We can call `assays` to get the assay data back and compare it with the slot data.
```
asys <- assays(rse)
identical(asys, rse@assays@data)
```
It is not surprising to see that they are identical, and I will expect the is no duplication of the data. However, when I check their internal data structure, it turns out that a duplication happened here(truncated output below)
```
> .Internal(inspect(rse@assays@data@listData$counts))
@0x000001c00e41aaf8 14 REALSXP g0c7 [REF(17),ATT] (len=100, tl=0) 0,0,0,0,0,...
> .Internal(inspect(asys@listData$counts))
@0x000001c00a1cb0a0 14 REALSXP g0c0 [REF(4),ATT]  wrapper [srt=-2147483648,no_na=0]
  @0x000001c018e1ad48 14 REALSXP g0c7 [REF(1),ATT] (len=100, tl=0) 0,0,0,0,0,...
```
Surprisingly, the duplication is not triggered by the `assays` accessor, but the `identical` function. The root cause is that the `assays` function will put a wrapper on the object it returns(`asys@listData$counts` in this example), and the wrapper duplicates its data when a data pointer is required at C level. This unnecessary duplication can bring a significant cost when the data is large. By looking into the `assays` function(signature "SummarizedExperiment"), I found where the wrapper is created
```
assays <- endoapply(assays, function(a) {
            a_dimnames <- dimnames(a)
            a_dimnames[1:2] <- x_dimnames
            dimnames(a) <- DelayedArray:::simplify_NULL_dimnames(a_dimnames)
            a
        })
```
The key function that creates the wrapper is `dimnames<-`. No matter whether the dimnames of an object will be changed, it always creates a wrapper on the object. Since there are many functions that rely on the data pointer to do the calculation(That's why I find it when I was working on the shared object: a shared object becomes unshared unexpectedly.), I suggest making the following change to prevent the creation of the wrapper if not necessary.
```
assays <- endoapply(assays, function(a) {
    a_dimnames <- dimnames(a)
    a_dimnames[1:2] <- x_dimnames
    a_dimnames <- DelayedArray:::simplify_NULL_dimnames(a_dimnames)
    if(!identical(dimnames(a), a_dimnames))
        dimnames(a) <- a_dimnames
    a
})
```
This will solve the wrapper problem and can provide some performance benefits for some functions.

Best,
Jiefei

**Comment by hpages** [comment]
Hi Jiefei,

Thanks for the catch. I made the change in SummarizedExperiment 1.19.3. However I'm experiencing problems with `git push` at the moment. Hopefully this will get sorted soon.

H.

**Comment by hpages** [comment]
I was finally able to push (bc1ca6ed79f387152eb37eec4dcf87d8f12aa3fe).

Closing now. Thanks again
