### ISSUE TITLE
Conversion to SingleCellExpriment object

### ISSUE THREAD

**Issue by zhli12** [Bioconductor/SummarizedExperiment#49]
Is there a way to convert SummarizedExperiment object to SingleCellExperiment object? My final goal is to create a Seurat object from the SummarizedExperiment object, but the conversion functions available can only be applied to SingleCellExperiment objects

**Comment by hpages** [comment]
Hi,

The SingleCellExperiment class extends the SummarizedExperiment class and is implemented in its own package (the **SingleCellExperiment** package). There are dozens of packages in Bioconductor that implement  SummarizedExperiment extensions and it's up to each of them to support coercion back and forth to SummarizedExperiment. In other words this is a question you need to ask to the SingleCellExperiment folks, either on the [Bioconductor support site](https://support.bioconductor.org/) (don't forget to tag your question with `SingleCellExperiment` and `SummarizedExperiment`), or [on GitHub](https://github.com/drisso/SingleCellExperiment/issues).

Best,
H.
