### ISSUE TITLE
import / export as loom

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/SummarizedExperiment#5]
@hpages I implemented an `.export_loom()` function on the [loom-export branch][3] to complement `makeSummarizedExperimentFromLoom()`, but I was wondering where it really belongs? In some ways it could go in HDF5Array, with functionality like `saveHDF5SummarizedExperimet()`. And ultimately it could well end up in a loom package (see also [loomR][1] and [hdf5r][2]). Suggestions?

There are some pretty severe limitations on functionality, e.g., not supporting GRangesList, any of the *List or other column classes, or even factor levels.

[3]: https://github.com/Bioconductor/SummarizedExperiment/tree/loom-export
[1]: https://github.com/mojaveazure/loomR
[2]: https://cran.r-project.org/package=hdf5r

**Comment by dvantwisk** [comment]
The features that @mtmorgan is discussing will be implemented in `LoomExperiment` https://github.com/Bioconductor/LoomExperiment.  Further discussion on functionality and features should occur there.
