### ISSUE TITLE
Subsetting

### ISSUE THREAD

**Issue by antagomir** [Bioconductor/SummarizedExperiment#55]
This may be too much asked but I am curious to check it out.

Let us first load some example `SE` data.
```
# Example data 
library(mia)
data(dmn_se)
se <- dmn_se
```

Subsetting based on `colData` requires explicit definition of the `colData`:

```
se[, colData(se)$pheno=="Obese"]
```

It would quite handy if one could subset this simply with:

```
se[, pheno=="Obese"]
```

It might not be too much assumed that, by default, the subsetting in such case would apply specifically to `colData` fields. Moreover, such change would not exclude the possibility of using more complex subsetting commands.

Similar points apply to `rowData` as well.

Perhaps this is against some design principles but might come handy anyway.

**Comment by vjcitn** [comment]
se[, se$pheno=="Obese"]

**Comment by antagomir** [comment]
Ah, right! Ok perhaps this is simple enough -
