### ISSUE TITLE
`combineCols()` and `combineRows()` not listed in 'Usage' section

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/SummarizedExperiment#61]
These are mentioned in the 'Combining' section but not up the top in the 'Usage'.
Want me to add them around here? 
https://github.com/Bioconductor/SummarizedExperiment/blob/7aff324fa3b4c24f78b7bc14eaff659b93d98c4b/man/SummarizedExperiment-class.Rd#L133-L136

**Comment by PeteHaitch** [comment]
Would you like a PR for this?

**Comment by hpages** [comment]
I'll add this. Thanks Pete for not giving up :wink:

**Comment by hpages** [comment]
Done in **SummarizedExperiment** 1.26.1 and 1.27.1

**Comment by PeteHaitch** [comment]
Thanks, Hervé
