### ISSUE TITLE
Curious about how Rd manuals are generated

### ISSUE THREAD

**Issue by mvfki** [Bioconductor/SummarizedExperiment#70]
Hi developers,

Thank you for having created such a great container. I don't have any bugs to report at this point. I have been developing another customized single-cell data container. I am struggling with organizing my code documentation so it can look intuitive enough for users and doesn't cost me too much time to work with. Then I recall these Bioconductor containers and came to look into your GitHub repositories. Surprisingly, I don't see any written documentation in your `R/` source code but you still have the Rd manuals properly generated. I wonder if you just "hand-made" the Rd manuals or if there are actually handy tools for this purpose that I should have known (I've been using `devtools::document()`). Appreciate it a lot if you can share your experience and tricks here.

Sincerely,
Yichen

**Comment by hpages** [comment]
Yes, the Rd files were hand-made, which is the traditional way. See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-R-documentation-files

**Comment by mvfki** [comment]
Ok got it. Thank you for your quick response. I'll try to see if I can manually do something with what I have now. 

Best

**Comment by mtmorgan** [comment]
It might be worth mentioning that one can use roxygen2 (and hence `devtools::document()`) to construct more-or-less arbitrary help pages. This approach and more 'advanced' features of roxygen2 might be useful, for instance ensuring that parameter arguments are defined consistently across help pages and for conveniently adding markup (e.g., italic, or inline code) without having to learn 'another' (assuming one knows markdown already, and the 'another' is Rd-flavored LaTeX) markup syntax.

I really appreciate the discipline that Hervé adopts of mapping one 'R' file to one help ('Rd' file) page; I think this helps impose a logical structure on the organization of the R code, and at the same time helps the user identify related functionality. sing `@rdname` has helped me to do that in the roxygen2 context (documenting functions defined in the same R file to the same help page).
