### ISSUE TITLE
SummarizedExperiment() constructor with SummarizedExperiment given as argument should return the same SummarizedExperiment

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/SummarizedExperiment#8]
I need to make a suggestion for a slight change in `SummarizedExperiment`.  The constructor for a `SummarizedExperiment` or `RangedSummarizedExperiment` is `SummarizedExperiment()`.  Given an existing `RangedSummarizedExperiment` object, `rse`, I would expect running the constructor on an existing object, it should simply return the same object.  This is not the case, as it instead returns a new object with the existing object stored as an assay.
```
> example(SummarizedExperiment)
> rse
class: RangedSummarizedExperiment
dim: 200 6
metadata(0):
assays(1): counts
rownames: NULL
rowData names(1): feature_id
colnames(6): A B ... E F
colData names(1): Treatment

> rse2 <- SummarizedExperiment(rse)
> rse2
class: SummarizedExperiment
dim: 200 6
metadata(0):
assays(1): ''
rownames: NULL
rowData names(0):
colnames(6): A B ... E F
colData names(0):

> assays(rse2)[[1]]
class: RangedSummarizedExperiment
dim: 200 6
metadata(0):
assays(1): counts
rownames: NULL
rowData names(1): feature_id
colnames(6): A B ... E F
colData names(1): Treatment
```
The constructor should return the same object if used on the constructor, correct?  If so, this change should be implemented.

**Comment by LiNk-NY** [comment]
Hi Daniel, @dvantwisk 
I guess the proposed change would something along the lines of : 

```
setMethod("SummarizedExperiment", "SummarizedExperiment",
    function(assays, ...)
{
   assays
}
```

*OR*
You could use the function to reconstruct the `SummarizedExperiment` although
you don't get the exact `SummarizedExperiment` back: 

```
SummarizedExperiment(assays(assays), ...)
```

**Comment by lawremi** [comment]
I'm curious about the use case here. I don't think there's a general expectation that 
```
x <- Constructor()
identical(x, Constructor(x))
```
Should return `TRUE` or even succeed.  In this case, the current behavior, treating the SE as an assay matrix, seems the most intuitive to me.

**Comment by mtmorgan** [comment]
The behavior is present in, for instance
```
> df = DataFrame(x=1:5)
> DataFrame(df)
DataFrame with 5 rows and 1 column
          x
  <integer>
1         1
2         2
3         3
4         4
5         5
> 
```

**Comment by LiNk-NY** [comment]
@mtmorgan @dvantwisk @lawremi 
Yes, the behavior is present in other List-type classes as well. I wonder if `SummarizedExperiment` should follow.

Here are more examples:
:smile: 
```
library(MultiAssayExperiment)
ex <- ExperimentList(exp = matrix())
ExperimentList(ex)
```
and 

```
library(GenomicRanges)
example(GRangesList)
GRangesList(grl)
```
