### ISSUE TITLE
`?SummarizedExperiment` redirects to the docs for `RangedSummarizedExperiment`

### ISSUE THREAD

**Issue by lazappi** [Bioconductor/SummarizedExperiment#80]
I have just noticed (for me at least) that using `?SummarizedExperiment` opens the docs for `RangedSummarizedExperiment` as does using any links etc. Possibly I'm doing something stupid but I've tried with devel, the current release and previous release in RStudio and on the command line and I haven't had any luck accessing the `SummarizedExperiment` page interactively. It is still included in the manual on website though.

**Comment by PeteHaitch** [comment]
> I haven't had any luck accessing the SummarizedExperiment page interactively

This will do it: 

```r
?`SummarizedExperiment-class`
```

R at the terminal, R.app, and RStudio should show this in the autocomplete dropdown menu if you type `?Summ` or similar and hit tab at the command line (provided **SummarizedExperiment** is attached) but my experience is that RStudio does a better job of inserting the ` characters needed to handle the hyphen in the name.

**Comment by lazappi** [comment]
Ok, that works. But I still think it's not ideal that `?SummarizedExperiment` doesn't take you to the correct object (or a package page) and the links between the `RangedSummarizedExperiment` page (or anything else) and the `SummarizedExperiment` page don't work.

**Comment by vjcitn** [comment]
This package was not documented with roxygen.  So the man pages are composed manually.  For some reason the \alias{SummarizedExperiment} entry is in RangedSummarizedExperiment-class.Rd ... and
```
## Constructor

# See ?RangedSummarizedExperiment for the constructor function.

```
is present in SummarizedExperiment-class.Rd.  I would wonder what @hpages would think about moving the \alias{SummarizedExperiment} to the SummarizedExperiment-class.Rd, and adding a note to the RangedSE doc to indicate where the basic constructor is found, indicating that the rowRanges argument, when used, will produce a RangedSE.

I seem to remember some discussion about deprecating RangedSummarizedExperiment as it isn't really needed?  An SE may or may not have non-null rowRanges.

**Comment by hpages** [comment]
> I would wonder what @hpages would think about moving the \alias{SummarizedExperiment} to the SummarizedExperiment-class.Rd, and adding a note to the RangedSE doc to indicate where the basic constructor is found

Done in **SummarizedExperiment** 1.35.1 (see commit c5b7ca2f8d975af13a18b3b5931449f092657f5c).

> I seem to remember some discussion about deprecating RangedSummarizedExperiment as it isn't really needed? An SE may or may not have non-null rowRanges.

Agreed that it would kind of make sense to collapse RangedSummarizedExperiment and SummarizedExperiment into a single class. Not an easy/light thing to do at this point though with so many classes that extend RangedSummarizedExperiment.

**Comment by hpages** [comment]
I'm closing this.

@vjcitn Please open a new issue to request/discuss deprecation of RangedSummarizedExperiment if you feel this is worth pursuing.
