### ISSUE TITLE
Add saveRDS() method for SummarizedExperiment derivatives

### ISSUE THREAD

**Issue by hpages** [Bioconductor/SummarizedExperiment#83]
Once https://github.com/Bioconductor/BiocGenerics/issues/18 is completed, add a `saveRDS()` method for SummarizedExperiment derivatives that throws an error if the object contains out-of-memory assays. The error message should point the user to `saveHDF5SummarizedExperimernt()`.

**Comment by lambdamoses** [comment]
Do you need me to PR? Also, what about types of `DelayedArray`s other than HDF5 that are out of memory?

**Comment by hpages** [comment]
> Do you need me to PR?

I'll take care of this, but thanks for the offer.

> Also, what about types of DelayedArrays other than HDF5 that are out of memory?

Good question. Note that `saveHDF5SummarizedExperiment(x)` is agnostic of the exact DelayedArray backends that are used for the individual assays in `x`. In other words, it will write all the assays to HDF5 regardless of whether they are currently stored in tiledb, HDF5, or another format. However, we could consider introducing other `save*SummarizedExperiment()` functions if we want the ability to save to other formats.

There's also the question of what's the best way to detect that an assay uses an out-of-memory representation. I'm considering introducing a new generic for that e.g. `is_out_of_memory()` (or something like that, still need to think about a good name). With the following methods:
- a default method that returns `FALSE`;
- a method for DelayedArray objects that returns `TRUE` if at least one of the seeds is itself out-of-memory;
- methods for the various "Seed objects" defined in the **HDF5Array** and **TileDBArray** packages that return `TRUE`;
- a method for SummarizedExperiment derivatives that returns `TRUE` if at least one of the assays is out-of-memory.

Working on it...

**Comment by hpages** [comment]
With **SummarizedExperiment** 1.35.2:
```
example(SummarizedExperiment)

containsOutOfMemoryData(cmb1)
# [1] FALSE

containsOutOfMemoryData(cmb2)
# [1] FALSE

containsOutOfMemoryData(cmb3)
# [1] TRUE

saveRDS(cmb1, "cmb1.rds")  # ok

saveRDS(cmb2, "cmb2.rds")  # ok

saveRDS(cmb3, "cmb3.rds")
# Error in saveRDS(cmb3, "cmb3.rds") : 
#   SummarizedExperiment object contains out-of-memory data so cannot be
#   serialized reliably. Please use saveHDF5SummarizedExperiment() from the
#   HDF5Array package instead. Also see '?containsOutOfMemoryData' in the
#   BiocGenerics package for some context.
```
